routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StartController;
use App\Http\Controllers\StartUpController;
use App\Http\Controllers\UserController;
 
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::get('reg', [StartUpController::class, 'index']);
Route::resource('start', StartController::class)->middleware('XssSanitization');
Route::get('success', function () { return view('finish');});
Route::post('dologin', [StartController::class, 'login'])->name('dologin')->middleware('XssSanitization');
Route::resource('dashboard', UserController::class);
Route::get('changepassword', [UserController::class, 'changepassword']);
Route::post('changepass', [UserController::class, 'changepass'])->name('changepass');
Route::get('logout', [UserController::class, 'logout']);
Route::get('projects', [UserController::class, 'projects']);
Route::get('newproject', [UserController::class, 'newproject']);
Route::post('newproj', [UserController::class, 'newproj'])->name('newproj');
Route::get('viewproj/{pid}', [UserController::class, 'viewproject']);
Route::get('editproj/{pid}', [UserController::class, 'editproject']);
Route::post('upproj', [UserController::class, 'upproj'])->name('upproj');
Route::get('projectusers', [UserController::class, 'projectusers']);
Route::post('newprojuser', [UserController::class, 'newprojuser'])->name('newprojuser');
Route::get('removeproj/{id}', [UserController::class, 'removeproj'])->name('removeproj');
Route::get('assignprojects', [UserController::class, 'assignprojects']);
Route::get('survey', [UserController::class, 'survey']);
Route::post('surveytest', [UserController::class, 'surveytest'])->name('surveytest');
//admin
Route::get('alogin', [StartUpController::class, 'alogin']);
Route::post('adlogin', [StartController::class, 'adminlogin'])->name('adlogin')->middleware('XssSanitization');
Route::get('admindashboard', [UserController::class, 'admindashboard']);
Route::get('aprojects', [UserController::class, 'aprojects']);
Route::get('aviewproj/{pid}', [UserController::class, 'aviewproject']);
Route::get('aeditproj/{pid}', [UserController::class, 'aeditproject']);
Route::post('aupproj', [UserController::class, 'aupproj'])->name('aupproj');
Route::get('deleteproj/{id}', [UserController::class, 'deleteproj'])->name('deleteproj');
Route::get('aprojectusers', [UserController::class, 'aprojectusers']);
Route::get('removeuser/{id}', [UserController::class, 'removeuser'])->name('removeuser');


 

resources/views/adminlogin.blade.php
<!doctype html>
<html lang="en-US">
	
 
<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no" />
		<title>.:: My Projects</title>
		
		<!-- Optional - Google font -->
		<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Gafata" />
		
		<!-- Required - Icon font -->
		<link rel="stylesheet" href="{{asset('css/font-awesome.min.css') }} " />
		
		<!-- Required - Bootstrap CSS -->
		<link rel="stylesheet" href="{{asset('css/bootstrap.min.css') }}" /> 
		
		<!-- Required - Form style -->
		<link rel="stylesheet" href="{{asset('css/flat-form.css') }}" /> 
		
		<!-- NOT required - Page style -->
<link rel="stylesheet" href="{{asset('css/page-style.css') }}" /> 
<script type="text/javascript" src="{{asset('js/jquery-1.11.3-jquery.min.js') }}"></script>
<script type="text/javascript" src="{{asset('js/validation.min.js') }}"></script>
<script type="text/javascript" src="{{asset('js/script.js') }}"></script>
	</head>
	
	<body>
		<div class="container">
			<header class="header">
				<h1>My Projects</h1>
			</header>
			
			<div class="content">
				<aside class="col-sm-4 col-md-3 sidebar">
					<ul class="nav nav-pills nav-stacked">
						<li class="active"><a href="{{env('APP_URL')}}">Home</a> </li>
                        <li><a href="reg">Register</a> </li>
                         <li><a href="alogin">Admin Login</a> </li>
					</ul>
				</aside>
				
				<article class="col-sm-8 col-md-9">
				
					<!-- START Login form -->
					
					<div class="row">
					
						<!-- Login form -->
						<div class="col-md-12">
							<div class="panel panel-form">
								<!-- Form header -->
								<div class="panel-heading">
									<h2 class="title">Admin Login</h2>
									 
								</div>
								
								<div class="panel-body">
					
        
       
       @if ($errors->any())		 <hr />
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                {{ $error }} 
            @endforeach
        </ul>
    </div>
@endif
                                    <form role="form" class="form-signin" method="post" id="login-form" action="{{ route('adlogin') }}"   autocomplete="off">
      
       @csrf
       
        
        
										<!-- Username or email -->
										<div class="form-group">
											<label for="email" class="control-label">Username</label>
											<div class="has-feedback">
												<input type="text" class="form-control" id="username" name = "username" autocomplete= "off" />
												<span class="fa fa-user form-control-feedback" aria-hidden="true"></span>
                                                  <span id="check-e"></span>
											</div>
										</div>
										
										<!-- Password -->
										<div class="form-group">
											<label for="password" class="control-label">Password</label>
											<div class="has-feedback">
												<input type="password" class="form-control" id="password" name="password"/>
												<span class="fa fa-lock form-control-feedback" aria-hidden="true"></span>
											</div>
										</div>
									 
										
										<!-- Logun button -->
										<div class="form-group">
											<button type="submit" class="btn btn-primary">Login</button>
											
											 
										</div>
									</form>
								</div>
							</div>
						</div>
						
						 
					<!-- END Login form -->
					
				</article>
				
				<div class="clearfix"></div>
			</div>
		</div>
		
		<!-- Required - jQuery -->
		<script src="{{asset('js/bootstrap.min.js') }}"></script>
		
		<!-- Required - Custom select -->
		<script src="{{asset('js/fancySelect.js') }}"></script>
		
		<script>
			$(document).ready(function() {
				$('.custom-select').fancySelect(); // Custom select
				$('[data-toggle="tooltip"]').tooltip() // Tooltip
			});
		</script> 
	</body>

 
</html>

resources/views/emailnotifier.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>My Projects</title>
</head>
<body>
    
    <h3>{{ $details['title'] }}</h3>
    <p>{{ $details['body'] }}<br><br>
    {{ $details['info'] }}<br><br>
     Email Address: {{ $details['email'] }}<br><br>
      Password: {{ $details['passkey'] }}<br><br>
       Fullnames No: {{ $details['fullnames'] }}
   </p>
    <p>Regards</p> 
     <br>My Projects
</body>
</html>

resources/views/finish.blade.php
<!doctype html>
<html lang="en-US">
	
 
<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no" />
		<title>.:: My Projects</title>
		
		<!-- Optional - Google font -->
		<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Gafata" />
		
		<!-- Required - Icon font -->
		<link rel="stylesheet" href="{{asset('css/font-awesome.min.css') }} " />
		
		<!-- Required - Bootstrap CSS -->
		<link rel="stylesheet" href="{{asset('css/bootstrap.min.css') }}" /> 
		
		<!-- Required - Form style -->
		<link rel="stylesheet" href="{{asset('css/flat-form.css') }}" /> 
		
		<!-- NOT required - Page style -->
<link rel="stylesheet" href="{{asset('css/page-style.css') }}" /> 
<script type="text/javascript" src="{{asset('js/jquery-1.11.3-jquery.min.js') }}"></script>
<script type="text/javascript" src="{{asset('js/validation.min.js') }}"></script>
<script type="text/javascript" src="{{asset('js/script.js') }}"></script>
	</head>
	
	<body>
     @empty(session('status'))
           {!  <script type="text/javascript">
			alert("Session expired!\nYou will be redirected to the home page shortly...");
			window.location = "{{env('APP_URL')}}";
		</script>  !}
    
@endempty   
		<div class="container">
			<header class="header">
				<h1>My Projects</h1>
			</header>
			
			<div class="content">
				<aside class="col-sm-4 col-md-3 sidebar">
					<ul class="nav nav-pills nav-stacked">
						<li class="active"><a href="{{env('APP_URL')}}">Home</a> </li>
					</ul>
				</aside>
				
				<article class="col-sm-8 col-md-9">
					<div class="col-md-8 col-md-offset-2">
					
						<!-- START Registration form -->
						
						<div class="panel panel-form">
							<!-- Form header -->
							 
                            
                            
                            
							
							<div class="panel-body">
								   
                                  <form name="form1" id="form1"  enctype="multipart/form-data" autocomplete="off">
        <div class="row">
          <div class="input-field col s12 center">
             
          <p class="center login-form-text" style = "font-weight: bold; color: #104E8B; font-size: 25px;">  REGISTRATION</p>
                <p class="center login-form-text" style = "color:#090; font-size: 25px; font-weight:bold">
                
           
                
                @if (session('status'))
    
        {{ session('status') }}
  
@endif </p>
                 <p style="font-size:14px">Your Account has Been Successfully Created.</p>
    <p style="font-size:14px">Your Account Info  is as follows:<br><br>
      <span id="ss"><b>Email Address</b>: @if (session('email'))
    
        {{ session('email') }}
  
@endif <br>
      <b>Password</b>: @if (session('passkey'))
    
        {{ session('passkey') }}
  
@endif </span><br><br>
    Please note these down and do not share your password with anyone.<br><br>A copy of this info will be sent to your email address at  {{ session('email') }} <br><br>If you cannot find the email in your Inbox, do check your Spam</p>
	<div> 
	  
	</div>
          </div>
        </div>
       
       
       
       
       
     
        
          <div class="row margin">
          <div class="input-field col s12">
           
          <a href="{{env('APP_URL')}}">  <input type= "button" name = "submit" value = "CLICK TO CONTINUE"  style = "width: 100%; padding: 9px; background: #1C86EE; color: white; border: 0px; " > </a>
          <br><br>
          </div>
        </div>
        
        </form>
							</div>
							
						 
					
					</div>
				</article>
				
				<div class="clearfix"></div>
			</div>
		</div>
		
		<!-- Required - jQuery -->
		<script src="{{asset('js/bootstrap.min.js') }}"></script>
		
		<!-- Required - Custom select -->
		<script src="{{asset('js/fancySelect.js') }}"></script>
		
		<script>
			$(document).ready(function() {
				$('.custom-select').fancySelect(); // Custom select
				$('[data-toggle="tooltip"]').tooltip() // Tooltip
			});
		</script> 
	</body>

 
</html>

resources/views/home.blade.php
<!doctype html>
<html lang="en-US">
	
 
<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no" />
		<title>.:: My Projects</title>
		
		<!-- Optional - Google font -->
		<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Gafata" />
		
		<!-- Required - Icon font -->
		<link rel="stylesheet" href="{{asset('css/font-awesome.min.css') }} " />
		
		<!-- Required - Bootstrap CSS -->
		<link rel="stylesheet" href="{{asset('css/bootstrap.min.css') }}" /> 
		
		<!-- Required - Form style -->
		<link rel="stylesheet" href="{{asset('css/flat-form.css') }}" /> 
		
		<!-- NOT required - Page style -->
<link rel="stylesheet" href="{{asset('css/page-style.css') }}" /> 
<script type="text/javascript" src="{{asset('js/jquery-1.11.3-jquery.min.js') }}"></script>
<script type="text/javascript" src="{{asset('js/validation.min.js') }}"></script>
<script type="text/javascript" src="{{asset('js/script.js') }}"></script>
	</head>
	
	<body>
		<div class="container">
			<header class="header">
				<h1>My Projects</h1>
			</header>
			
			<div class="content">
				<aside class="col-sm-4 col-md-3 sidebar">
					<ul class="nav nav-pills nav-stacked">
						<li class="active"><a href="{{env('APP_URL')}}">Home</a> </li>
                        <li><a href="reg">Register</a> </li>
                         <li><a href="alogin">Admin Login</a> </li>
					</ul>
				</aside>
				
				<article class="col-sm-8 col-md-9">
				
					<!-- START Login form -->
					
					<div class="row">
					
						<!-- Login form -->
						<div class="col-md-6">
							<div class="panel panel-form">
								<!-- Form header -->
								<div class="panel-heading">
									<h2 class="title">Login</h2>
									<p>Don't have an account? <a href="reg">Create one</a>.</p>
								</div>
								
								<div class="panel-body">
					
        
       
       @if ($errors->any())		 <hr />
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                {{ $error }} 
            @endforeach
        </ul>
    </div>
@endif
                                    <form role="form" class="form-signin" method="post" id="login-form" action="{{ route('dologin') }}"   autocomplete="off">
      
       @csrf
       
        
        
										<!-- Username or email -->
										<div class="form-group">
											<label for="email" class="control-label">Email</label>
											<div class="has-feedback">
												<input type="email" class="form-control" id="email" name = "email" autocomplete= "off" value="{{ old('email') }}"/>
												<span class="fa fa-user form-control-feedback" aria-hidden="true"></span>
                                                  <span id="check-e"></span>
											</div>
										</div>
										
										<!-- Password -->
										<div class="form-group">
											<label for="password" class="control-label">Password</label>
											<div class="has-feedback">
												<input type="password" class="form-control" id="password" name="password"/>
												<span class="fa fa-lock form-control-feedback" aria-hidden="true"></span>
											</div>
										</div>
										
										<!-- Remember checkbox -->
										<div class="form-group">
											<div class="checkbox">
												<label class="custom-option toggle" data-off="OFF" data-on="ON">
													<input type="checkbox" id="remember" name="remember" value="1" />
													<span class="button-checkbox"></span>
												</label>
												<label for="remember">Remember Me</label>
											</div>
										</div>
										
										<!-- Logun button -->
										<div class="form-group">
											<button type="submit" class="btn btn-primary">Login</button>
											
											 
										</div>
									</form>
								</div>
							</div>
						</div>
						
						<!-- Login with social network -->
						<div class="col-md-6">
							<h2 class="text-center">Login with a social network</h2>
							
							<button type="button" class="btn btn-block btn-facebook btn-lg btn-left-icon">
								<span class="fa fa-facebook" aria-hidden="true"></span> Login with Facebook
							</button>
							
							<button type="button" class="btn btn-block btn-twitter btn-lg btn-left-icon">
								<span class="fa fa-twitter" aria-hidden="true"></span> Login with Twitter
							</button>
							
							<button type="button" class="btn btn-block btn-google btn-lg btn-left-icon">
								<span class="fa fa-google-plus" aria-hidden="true"></span> Login with Google Plus
							</button>
						</div>
						
					</div>
					
					<!-- END Login form -->
					
				</article>
				
				<div class="clearfix"></div>
			</div>
		</div>
		
		<!-- Required - jQuery -->
		<script src="{{asset('js/bootstrap.min.js') }}"></script>
		
		<!-- Required - Custom select -->
		<script src="{{asset('js/fancySelect.js') }}"></script>
		
		<script>
			$(document).ready(function() {
				$('.custom-select').fancySelect(); // Custom select
				$('[data-toggle="tooltip"]').tooltip() // Tooltip
			});
		</script> 
	</body>

 
</html>

resources/views/registration.blade.php
<!doctype html>
<html lang="en-US">
	
 
<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no" />
		<title>.:: My Projects</title>
		
		<!-- Optional - Google font -->
		<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Gafata" />
		
		<!-- Required - Icon font -->
		<link rel="stylesheet" href="{{asset('css/font-awesome.min.css') }} " />
		
		<!-- Required - Bootstrap CSS -->
		<link rel="stylesheet" href="{{asset('css/bootstrap.min.css') }}" /> 
		
		<!-- Required - Form style -->
		<link rel="stylesheet" href="{{asset('css/flat-form.css') }}" /> 
		
		<!-- NOT required - Page style -->
<link rel="stylesheet" href="{{asset('css/page-style.css') }}" /> 
<script type="text/javascript" src="{{asset('js/jquery-1.11.3-jquery.min.js') }}"></script>
<script type="text/javascript" src="{{asset('js/validation.min.js') }}"></script>
<script type="text/javascript" src="{{asset('js/script.js') }}"></script>
	</head>
	
	<body>
		<div class="container">
			<header class="header">
				<h1>My Projects</h1>
			</header>
			
			<div class="content">
				<aside class="col-sm-4 col-md-3 sidebar">
					<ul class="nav nav-pills nav-stacked">
						<li class="active"><a href="{{env('APP_URL')}}">Home</a> </li>
					</ul>
				</aside>
				
				<article class="col-sm-8 col-md-9">
					<div class="col-md-8 col-md-offset-2">
					
						<!-- START Registration form -->
						
						<div class="panel panel-form">
							<!-- Form header -->
							<div class="panel-heading">
								<h2 class="title">Registration</h2>
								<p>Already have an account? <a href="{{env('APP_URL')}}">Sign in</a>.</p>
							</div>
                            
                            
                            
							
							<div class="panel-body">
								  @if ($errors->any())
       
       <div class="row" style="color:#F00">
            <div class="m12 s12 col">
                <div class="card-panel red darken-1">
                    <div class="row">
                        <div class="col l8 white-text">
                            <h5>Error!</h5>
                           <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
                        </div>
                       
                    </div>
                </div>
            </div>
        </div>
   
@endif
                                 <form role="form" name="form1" id="form1" method="post" action="{{ route('start.store') }}"   autocomplete="off"> @csrf
									<!-- Name and gender -->
									<div class="row">
										<div class="col-sm-12 form-group">
											<label for="name" class="control-label">Name</label>
                                            <div class="has-feedback">
											<input type="text" class="form-control" id="name"  name="fname" required/>
                                            <span class="fa fa-user form-control-feedback" aria-hidden="true"></span>
                                            <p class="help-block">At least 8 characters long.</p>
											</div>
										</div>
										
										 
									</div>
									
									
									
									<!-- Passwords -->
									<div class="row">
										<div class="col-sm-6 form-group">
											<label for="password1" class="control-label">Password <span class="required-field">*</span></label>
											<div class="has-feedback">
												<input type="password" class="form-control" id="password1"  name="passkey"required />
												<span class="fa fa-lock form-control-feedback" aria-hidden="true"></span>
											</div>
											<p class="help-block">At least 6 characters long.</p>
										</div>
										
										<div class="col-sm-6 form-group">
											<label for="password2" class="control-label">Confirm password <span class="required-field">*</span></label>
											<div class="has-feedback">
												<input type="password" class="form-control" id="password2" name="password2" required/>
												<span class="fa fa-lock form-control-feedback" aria-hidden="true"></span>
											</div>
										</div>
									</div>
									
									
									<!-- Email -->
									<div class="form-group">
										<label for="email" class="control-label">Email <span class="required-field">*</span></label>
										<div class="has-feedback">
											<input type="email" class="form-control" id="email" name="email"/>
											<span class="fa fa-envelope form-control-feedback" aria-hidden="true"></span>
										</div>
									</div>
									 
									 <!-- Phone Number -->
									<div class="row">
										<div class="col-sm-12 form-group">
											<label for="name" class="control-label">Phone Number <span class="required-field">*</span></label>
                                            <div class="has-feedback">
											<input type="text" class="form-control" id="phoneno" name="phoneno" required/>
                                            <span class="fa fa-user form-control-feedback" aria-hidden="true"></span>
											</div>
										</div>
										
										 
									</div>
									 
									
									<!-- Agree static text -->
									<div class="form-group">
										<p class="form-control-static">
											Do you agree to the <a href="#">User Agreement</a> and <a href="#">Privacy Policy</a>,
											and terms incorporated therein?
										</p>
									</div>
									
									<!-- Create button -->
									<div class="form-group text-center">
										<button type="submit" class="btn btn-primary">Agree and Create Account</button>
									</div>
								</form>
							</div>
							
							<!-- Form footer -->
							<div class="panel-footer">
								<span class="required-field">*</span> - required field
							</div>
						</div>
						
						<!-- END Registration form -->
					
					</div>
				</article>
				
				<div class="clearfix"></div>
			</div>
		</div>
		
		<!-- Required - jQuery -->
		<script src="{{asset('js/bootstrap.min.js') }}"></script>
		
		<!-- Required - Custom select -->
		<script src="{{asset('js/fancySelect.js') }}"></script>
		
		<script>
			$(document).ready(function() {
				$('.custom-select').fancySelect(); // Custom select
				$('[data-toggle="tooltip"]').tooltip() // Tooltip
			});
		</script> 
	</body>

 
</html>